services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentlabs_frontend
    ports:
      - '3000:80'
    environment:
      VITE_API_BASE: ${VITE_API_BASE}
    restart: unless-stopped
