services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE}
    container_name: job_platform_frontend
    ports:
      - '5173:80'
    environment:
      VITE_API_BASE: ${VITE_API_BASE}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - job_platform_network

networks:
  job_platform_network:
    external: true
